safe: false
lsi: false
pygments: true

relative_source: ../EXAMPLE/
destination: ../EXAMPLE/

# Settings for deploy rake task
# User branch: source (or anything that is not master) for user/organization
# Use branch: master for projects, can also be omitted
username: EXAMPLE
repo: EXAMPLE
branch: source

permalink: pretty

paginate: 10
paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml